config/routes.rb
Rails.application.routes.draw do
  post "posts/reservations/:post_id/new"=>"reservations#create"
  get "posts/reservations/:post_id/new" =>"reservations#new"
  get 'reservations/:id/index' =>"reservations#index"
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  post "users/:id/profile" => "users#compilation"
  get "users/:id/edit" => "users#edit"
  get "users/:id/account" => "users#account"
  get "users/:id/profile" =>"users#profile"
  post'users/create' => 'users#create'
  get "signup" => "users#new"
  get "users/:id/rooms"=>"users#rooms"
  get 'users/index'
  
  
  
  get "posts/search"=>"posts#search"
  post "posts/new" =>"posts#create"
  get "posts/new" =>"posts#new"
  get 'posts/index' =>"posts#index"
  get "posts/:id" =>"posts#show"
  get '/' =>'home#top'
  resources :reservations
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :r_image, RImageUploader
    validates :user_id,{presence:true}
    
    def self.search(search,free)
        if search 
            @posts = Post.where(['r_adress LIKE ?', "%#{search}%"])
        elsif free
            @posts = Post.where(['r_introduction LIKE ? OR r_name LIKE ?', "%#{free}%", "%#{free}%"])
        else
            @posts = Post.all
        end
    end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validates :start_date, {presence: true}
    validates :end_date, {presence: true}
    validates :people, {presence: true}
    validates :user_id, {presence: true}
    validates :post_id, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name,{presence:true}
    validates :email,{presence:true,uniqueness:true}

    def posts
        return Post.where(user_id: self.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end
    def authenticate_user
        if @current_user == nil
            flash[:notice] = "ログインが必要です"
            redirect_to("/login")
        end
    end
    def forbid_login_user
        if @current_user
            flash[:notice] = "すでにログインしています"
            redirect_to("/")
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, {only: [:create,:new,:show]}
  def index
    @posts = Post.all
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(
      r_name: params[:r_name],
      r_introduction: params[:r_introduction],
      r_price: params[:r_price],
      r_adress: params[:r_adress],
      r_image: params[:r_image],
      user_id: @current_user.id)
    if @post.save
      flash[:notice] = "ルームを登録しました！"
      redirect_to("/")
    else
      render action: "new"
    end
  end
  def search
    @posts = Post.search(params[:search],params[:free])
  end
  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user_id)
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @current_user.id != @posts.user_id
      flash[:notice] = "権限がありません"
      redirect_to("/")
    end
  end


  private
  def posts_params
    params.permit(:r_name,:r_introduction,:r_price,:r_adress,:r_image)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user
  def index
    @reservations = Reservation.where(user_id: @current_user.id)
  end
  def new
    @post = Post.find_by(id: params[:id])
    @reservation = Reservation.new
  end
  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @current_user.id != @posts.user_id
      flash[:notice] = "権限がありません"
      redirect_to("/")
    end
  end


  def create
    @post = Post.find_by(id: params[:id])
    @reservation = Reservation.new(
      start_date: params[:start_date],
      end_date: params[:end_date],
      people: params[:people],
      user_id: @current_user.id,
      post_id: params[:post_id],
      total_price: params[:total_price],
      p1_price: params[:p1_price]
    )
    if @reservation.save
      flash[:notice] = "予約を完了しました！"
      redirect_to("/")
    else
      flash[:notice] = "予約に失敗しました！"
      redirect_to("/")
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index , :edit, :account , :update ,:profile , :compilation]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update , :account , :profile , :compilation]}
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation],
      image:'default_user.jpg')
    if @user.save
      session[:user_id] = @user.id
      #log_in @user
      flash[:notice] = "Welcome to the Sample App!"
      redirect_to('/')
    else
      render action: "new"
    end
  end
  def edit
    @user = User.find_by(id: params[:id])
  end
  def account
    @user = User.find_by(id: params[:id])
  end
  def update
    @user = User.find_by(id: params[:id])
  end
  def profile
    @user = User.find_by(id: params[:id])
  end
  def compilation
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.introduction = params[:introduction]
    if params[:image]
    @user.image = "#{@user.id}.jpg"
    image = params[:image]
    File.binwrite("public/user_images/#{params[:id]}.jpg",image.read)
    end
    if @user.save
      flash[:notice] = "情報を更新しました"
      redirect_to("/users/#{@user.id}/profile")
      else
      render "/users/#{@user.id}/profile"
      end
  end

  def login_form
  end
  
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]            
      @password = params[:password]            
      render("users/login_form")
    end
  end
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to("/")
    end
  end
  def rooms
    @user = User.find_by(id: params[:id])
  end

  private
  def user_params
    params.permit(:name, :email, :password, :password_confirmation)
  end
  def profile_params
    params.permit(:image,:name,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top-container">
    <div class="center-container">
        <div class="flex">
            <div class="form_container">
                <h1 class="container_text">Potepan Shareでまだ体験したことのない旅をしよう</h1>
                <p>エリアorキーワード</p>
                <div class="container-form">
                    <%= form_with(url: posts_search_path,method: :get,local: true) do |f|%>
                        <%= f.text_field :search, placeholder:"エリア" %>
                        <%= f.submit '検索する', name: nil %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="middle">
    <div class=recomendContainer>
        <h1>おすすめエリア</h1>
        <ul class="area-imgs">
            <div class="link_img">
            <%= link_to posts_search_path(search: "東京")do %> 
            <li><span>東京</span><img class="areaImg" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg"></li>
            <% end %></div>
            <div class="link_img">
            <%= link_to posts_search_path(search: "大阪") do %> 
            <li><span>大阪</span><img class="areaImg" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg"></li>
            <% end %></div>
            <div class="link_img">
            <%= link_to posts_search_path(search: "京都") do %> 
            <li><span>京都</span><img class="areaImg" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg"></li>
            <% end %></div>
            <div class="link_img">
            <%= link_to posts_search_path(search: "札幌") do %> 
            <li><span>札幌</span><img class="areaImg" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg"></li>
            <% end %></div>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LodgingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
  <div class="header">
    <div class="header-left"><%= link_to image_tag("logo.png"), "/" %>
    <div class="header-left-form">
    <%= form_with(url: posts_search_path,method: :get,local: true) do |f|%>
  <%= f.text_field :free, placeholder:"キーワード" %>
  <%= f.submit '検索する', name: nil %>
    <% end %>
    
    </div>
</div>

    <div class="header-right">
    <% if @current_user %>
      <p class="top_user_name"><%= @current_user.name %></p>
      <img class="top_user_icon" src="<%= "/user_images/#{@current_user.image}" %>">
      <ul id="accordion" class="accordion">
        <li>
          <div class="link">M E N U<i class="fa fa-chevron-down"></i></div>
          <ul class="submenu">
            <li><%= link_to("ルーム登録", "/posts/new") %></li>
            <li><%= link_to("予約済ルーム一覧", "/reservations/#{@current_user.id}/index") %></li>
            <li><%= link_to("登録済ルーム一覧", "/users/#{@current_user.id}/rooms") %></li>
            <li><%= link_to("アカウント設定", "/users/#{@current_user.id}/account") %></li>
            <li><%= link_to("ログアウト", "/logout", {method: "post"}) %></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <div class="header_right2">
        <%= link_to("ログイン","/login",{class: "login-btn btn"})%>
        <%= link_to("登録する","/signup",{class: "signup-btn btn"}) %>
      </div>
    <% end %>
    </div>
  
  </div>
  </header>
  
  <% if flash[:notice] %>
    <div class="flash">
    <%= flash[:notice] %>
    </div>
  <% end %>
  <%= yield %>
  <footer class="footer">
  <p>© 2020 POTEPAN.INC.</p>
  </footer>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container-room">
    <h2>検索結果</h2>
    <div class="main-room">
        <% @posts.each do |post| %>
            <div class="outer-room">
                <div class="inner-room">
                    <%= link_to("/posts/#{post.id}",class:"no-underline") do %>
                    <div class="img-form-room">
                        <%= image_tag post.r_image.url,class: "img-room"%>
                    </div>
                    <div class="info-room">
                        <p class="room-name"><%= post.r_name %></p>
                        <p class="room-country"><%= post.r_adress%></p>
                        <p class="room-price"><%= post.r_price %></p>
                    </div>
                    <%end%>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/posts/new.html.erb
<%= form_with model:@posts do |f| %>
    <div class="all-wrapper">
        <div class="left-wrapper">
            <ul>
            <li>基本情報</li>
            </ul>
        </div>
        <div class="right-wrapper">
            <div class="form-wrapper">
                <div class="contents-wrapper">
                    <p class="top-contents">ルーム情報登録</p>
                </div>
                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents"> ルーム名</label>
                        <div class="icon-contents">
                            <%= f.text_field :r_name %>
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents">ルーム紹介 </label>
                        <div class="email-contents">
                            <%= f.text_area :r_introduction %>
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents">料金 </label>
                        <div class="email-contents">
                            <%= f.number_field :r_price %>
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents">住所 </label>
                        <div class="email-contents">
                            <%= f.text_field :r_adress %>
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents">ルーム画像 </label>
                        <div class="email-contents">
                            <%= f.file_field :r_image %>
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <p class="top-contents">
                        <%= f.submit "登録",class:"login-btn btn"  %>
                    </p>
                </div>
            </div>
        </div>
    </div>
<%end%>

app/views/posts/search.html.erb
<div class="container-room">
    <h2>検索結果</h2>
    <div class="main-room">
        <% @posts.each do |post| %>
        <div class="outer-room">
            <div class="inner-room">
                <%= link_to("/posts/#{post.id}",class:"no-underline") do %>
                    <div class="img-form-room">
                        <%= image_tag post.r_image.url,class: "img-room"%>
                    </div>
                        <div class="info-room">
                            <p class="room-name"><%= post.r_name %></p>
                            <p class="room-country"><%= post.r_adress%></p>
                            <p class="room-price"><%= post.r_price %></p>
                        </div>
                <%end%>
            </div>
        </div>
        <%end%>
    </div>
</div>

app/views/posts/show.html.erb
<div class="room-show">
    <div class="room_top">
        <h1 class="room_title"><%=@post.r_name%></h1>
        <p class="room_address"><%= @post.r_adress%></p>
    </div>
    <div class="room-contents">
        <div class="room_info">
            <%= image_tag @post.r_image.url,class:"room_image"%>
            <div class="room_show_contents">
                <div class="room_image_wrapper">
                    <img class="room_icon" src="<%="/user_images/#{@user.image}"%>">
                </div>
                <div class="room_">
                    <p class="room_name"><%= @user.name%>さんのお部屋</p>
                    <p class="room_user_introduction"><%= @user.introduction%></p>
                </div>
            </div>
                <div class="room_comment">
                    <p><%= @post.r_introduction%></p>
                </div>
        </div>
        <%= form_with(url: "reservations/#{@post.id}/new" , method: :get) do |f| %>
            <div class="room_info2">
                <div class="room_info_main">
                    <div class="room_info_navi">
                        <p class="price_navi"><%="¥#{@post.r_price} / 日 "%></p>
                            <div class="room_form-group">
                                <label for="start_day">開始日</label>
                                <%= f.date_field :start_date,class:"room_form" %>
                            </div>
                            <div class="room_form-group">
                                <label for="end_day">終了日</label>
                                <%= f.date_field :end_date ,class:"room_form" %>
                            </div>
                            <div class="room_form-group">
                                <label for="number_of_people">人数</label>
                                <%= f.number_field :people ,class:"room_form" %>
                            </div>
                        <%= f.hidden_field :user_id,:value => @current_user.id%>
                        <%= f.hidden_field :post_id,:value => @post.id%>
                        <%= f.hidden_field :p1_price,:value => @post.r_price%>
                        <div class="contents-wrapper">
                            <p class="top-contents">
                            <%= f.submit "予約する",class:"login-btn btn" %>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/reservations/index.html.erb
<div class="reservations-index">
    <table>
        <thead>
            <tr>
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>合計料金</th>
                <th>開始日</th>
                <th>終了日</th>
                <th>予約確定日</th>
            </tr>
        </thead>
        <tbody>
        <% @reservations.each do |reservation| %>
            <% @posts = Post.where(id: reservation.post_id) %>
            <% @posts.each do |post| %>
                <tr>
                    <td class="td-img"><%= link_to image_tag(post.r_image.url,class: "user_img-room"),"/posts/#{post.id}"%></td>
                    <td class="td-posts-name"><%= post.r_name%></td>
                    <td class="td-posts-content"><%= post.r_introduction%></td>
                    <td class="td-price">¥<%= reservation.total_price %></td>
                    <td class="td-start"><%= reservation.start_date.to_s(:datetime_jp)%></td>
                    <td class="td-end"><%= reservation.end_date.to_s(:datetime_jp)%></td>
                    <td class="td-date"><%= post.created_at.to_s(:datetime_jp)%></td>
                </tr>
            <%end%>
        <% end %>
        </tbody>
    </table>
</div>

app/views/reservations/new.html.erb
<div class="reservations-wrapper">
    <div class="form-wrapper">
        <div class="contents-wrapper">
            <p class="top-contents">予約確認</p>
        </div>
        <p class="price_navi">¥<%= params[:p1_price] %>/日</p>

        <%= form_with(model:@reservations,url: "") do |f| %>
            <div class="contents-wrapper">
                <div class="contents-row">
                    <label class="span-contents">開始日 </label>
                    <div class="email-contents">
                    <%= f.date_field :start_date,value:params[:start_date],readonly: true %>
                    </div>
                </div>
            </div>

            <div class="contents-wrapper">
                <div class="contents-row">
                    <label class="span-contents">終了日 </label>
                    <div class="email-contents">
                    <%= f.date_field :end_date, value:params[:end_date],readonly: true %>
                    </div>
                </div>
            </div>

            <div class="contents-wrapper">
                <div class="contents-row">
                    <label class="span-contents">1人/1泊の金額 </label>
                    <div class="email-contents">
                    <p><%= f.number_field :p1_price ,class:"room_form",value:params[:p1_price],readonly: true %></p>
                    </div>
                </div>
            </div>

            <div class="contents-wrapper">
                <div class="contents-row">
                    <label class="span-contents">人数 </label>
                    <div class="email-contents">
                    <%= f.number_field :people ,class:"room_form",value:params[:people],readonly: true %>
                    </div>
                </div>
            </div>

            <div class="contents-wrapper">
                <div class="contents-row">
                    <label class="span-contents">合計金額 </label>
                    <div class="email-contents">
                    <%= f.number_field :total_price ,class:"room_form",value: params[:p1_price].to_i * params[:people].to_i * ((params[:end_date].to_date) - (params[:start_date].to_date)).to_i,readonly: true %>
                    </div>
                </div>
            </div>

            <div class="contents-wrapper">
                <p class="top-contents">
                    <%= f.submit "予約する",class:"login-btn btn"  %>
                </p>
            </div>
        <%end%>
    </div>
</div>

app/views/users/account.html.erb
<div class="all-wrapper">
    <div class="left-wrapper">
        <ul>
            <li><%= link_to("アカウント","/users/#{@user.id}/account")%></li>
            <li><%= link_to("プロフィール","/users/#{@user.id}/profile")%></li>
        </ul>
    </div>

    <div class="right-wrapper">
        <div class="form-wrapper">
            <div class="contents-wrapper">
                <p class="top-contents">アカウント</p>
            </div>

            <div class="contents-wrapper">
                <div class="contents-row">
                    <label class="span-contents">メールアドレス </label>
                    <div class="email-contents"><%= @user.email%></div>
                </div>
            </div>

            <div class="contents-wrapper">
                <div class="contents-row">
                    <label class="span-contents">パスワード </label>
                    <div class="email-contents">＊＊＊＊＊＊＊＊</div>
                </div>
            </div>

            <div class="contents-wrapper">
                <%= link_to("編集","/users/#{@user.id}/edit",class:"login-btn btn")%>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<%= form_with model:@users do |f| %>
    <div class="form-container">
        <div class="form-main">
            <p>アカウントを編集</p>
            <%= flash[:notice] %>
                <div class="form-inner">
                    <div class="form-group">
                        <%= f.text_field :email,value: @user.email,class:'form-one'%>
                    </div>
                    <div class="form-group">
                        <%= f.password_field :password,placeholder: "パスワード",class:'form-one' %>
                    </div>
                    <div class="form-group">
                        <%= f.password_field :password_confirmation,placeholder: "パスワード（確認）",class:'form-one' %>
                    </div>
                    <div class="form-group">
                        <%= f.password_field :password,placeholder: "パスワード（確認）",class:'form-one' %>
                    </div>
                </div>    
            <%= f.submit '編集する',class: 'btn login-btn login-btn-a' %>
        </div>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="main users-index">
    <div class="container">
        <h1 class="users-heading">ユーザー一覧</h1>
        <% @users.each do |user| %>
            <div class="users-index-item">
                <div class="user-right">
                    <%=user.name %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/users/login_form.html.erb
<%= form_with(url: login_path, local: true) do |f| %>
    <div class="form-container">
        <div class="form-main">
            <h3>ログイン</h3>
            <% if @error_message %>            
                <div class="form-error">            
                    <%= @error_message %>            
                </div>            
            <% end %>
                <div class="form-inner">
                    <div class="form-group">
                        <span class="form-red">必須</span>
                        <%= f.text_field :email,placeholder: "メールアドレス",value: @email, class:'form-one' %>
                    </div>
                    <div class="form-group">
                        <span class="form-red">必須</span>
                        <%= f.password_field :password,placeholder: "パスワード",value:@password ,class:'form-one' %>
                    </div>
                </div>
            <%= f.submit 'ログイン', class: 'btn login-btn login-btn-a' %>
            <p class="login-btn-b"><a href="signup">新しいアカウントを作成</a></p>
        </div>
    </div>
<% end %>

app/views/users/new.html.erb
<%= form_with url:users_create_path do |f| %>
    <div class="form-container">
        <div class="form-main">
        <p>新しいアカウントを作成</p>
        <%= flash[:notice] %>
            <div class="form-inner">
                <% @user.errors.full_messages.each do |message| %>
                    <div class="form-error">
                        <%= message %>
                    </div>
                <% end %>
                    <div class="form-group">
                        <span class="form-red">必須</span>
                        <%= f.text_field :name,placeholder: "ユーザー名",value: @user.name,class:'form-one'  %>
                    </div>
                    <div class="form-group">
                        <span class="form-red">必須</span>
                        <%= f.text_field :email,placeholder: "メールアドレス",value: @user.email ,class:'form-one' %>
                    </div>
                    <div class="form-group">
                        <span class="form-red">必須</span>
                        <%= f.password_field :password,placeholder: "パスワード",class:'form-one' %>
                    </div>
                    <div class="form-group">
                        <span class="form-red">必須</span>
                        <%= f.password_field :password_confirmation,placeholder: "パスワード（確認）",class:'form-one' %>
                    </div>
            </div>
            <%= f.submit '新しいアカウントを作成', class: 'btn login-btn login-btn-a' %>
            <p class="login-btn-b"><a href="/login">すでにアカウントをお持ちの方はログイン</a></p>
        </div>
    </div>
<% end %>

app/views/users/profile.html.erb
<%= form_with model:@users do |f| %>
    <div class="all-wrapper">
        <div class="left-wrapper">
            <ul>
                <li><%= link_to("アカウント","/users/#{@user.id}/account")%></li>
                <li><%= link_to("プロフィール","/users/#{@user.id}/profile")%></li>
            </ul>
        </div>
        <div class="right-wrapper">
            <div class="form-wrapper">
                <div class="contents-wrapper">
                    <p class="top-contents">プロフィール</p>
                </div>

                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents"> </label>
                        <div class="icon-contents">
                            <img class="user_icon" src="<%= "/user_images/#{@user.image}" %>">
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents">アイコン画像 </label>
                        <div class="email-contents">
                            <%= f.file_field :image %>
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents">名前 </label>
                        <div class="email-contents">
                            <%= f.text_field :name,value: @user.name%>
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <div class="contents-row">
                        <label class="span-contents">自己紹介 </label>
                        <div class="email-contents">
                            <%= f.text_area :introduction,value: @user.introduction%>
                        </div>
                    </div>
                </div>

                <div class="contents-wrapper">
                    <p class="top-contents">
                        <%= f.submit "更新",class:"login-btn btn"  %>
                    </p>
                </div>
            </div>
        </div>
    </div>
<%end%>

app/views/users/rooms.html.erb
<div class="reservations-index">
    <table>
        <thead>
            <tr>
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>料金</th>
                <th>登録日</th>
            </tr>
        </thead>
        <% @user.posts.each do |post| %>
        <tbody>
                <tr>
                    <td class="td-img"><%= link_to image_tag(post.r_image.url,class: "user_img-room"),"/posts/#{post.id}"%></td>
                    <td class="td-posts-name"><%= post.r_name%></td>
                    <td class="td-posts-content"><%= post.r_introduction%></td>
                    <td class="td-price">¥<%= post.r_price%></td>
                    <td><%= post.created_at.to_s(:datetime_jp)%></td>
                </tr>
        </tbody>
        <% end %>
    </table>
</div>